### ISSUE TITLE
Time in the tweet

### ISSUE THREAD

**Issue by LyonelB** [dlnetworks/twittercast#3]
Hello,

I would add time in the tweet.
Is it possible? If yes, how ?

Best regards

**Comment by dlnetworks** [comment]
im not sure that would make sense considering all tweets are timestamped by twitter…

**Comment by LyonelB** [comment]
Yes I know.
But when we want to know what happened as at a specific time, it is easier to read the time in hh: mm that "there is 16 hours"

**Comment by dlnetworks** [comment]
I'll add options you can set on the config page for timestamp. It will include 12 and 24H format, time zone offset, and pre/append selection options.

I will try and get everything coded in over the weekend.

Twittercast.net

**Comment by dlnetworks** [comment]
set the current time/date to a var

`$date = date('m/d/Y h:i:s a', time());`

add the date var to the tweet output

`$twitterObj->post('/statuses/update.json', array('status' => $date.' - '.$title));`

**Comment by LyonelB** [comment]
Thank you
it works but as the variable $ time exchange between two applications of cron (wget), the same title appears several times: 
![tweet date](https://cloud.githubusercontent.com/assets/776493/19828679/347ee442-9dcd-11e6-9ba1-a32f3df3eb87.png)

**Comment by dlnetworks** [comment]
thats because your calling on the script with cron every *.. so its going to post each and every time you run the script when you have the time in there.. by default twitter will reject a tweet if its identical to the previous. that is why it you most likely didnt see multiple tweets before.. check your php error log and you should see the failed attempts.

what i do is keep a local file with the title in it, and compare that to what the *cast server is reporting, if the title is different than whats in the local file, run the script and update the local file with the new title, else do nothing
